//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECNICALSERVICES
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBtecnicalservicesEntities : DbContext
    {
        public DBtecnicalservicesEntities()
            : base("name=DBtecnicalservicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_BILLDETAIL> TBL_BILLDETAIL { get; set; }
        public virtual DbSet<TBL_BILLINFORMATION> TBL_BILLINFORMATION { get; set; }
        public virtual DbSet<TBL_CATEGORIES> TBL_CATEGORIES { get; set; }
        public virtual DbSet<TBL_CURRENT> TBL_CURRENT { get; set; }
        public virtual DbSet<TBL_DEFECTDETAIL> TBL_DEFECTDETAIL { get; set; }
        public virtual DbSet<TBL_DEPARTMAN> TBL_DEPARTMAN { get; set; }
        public virtual DbSet<TBL_NOTES> TBL_NOTES { get; set; }
        public virtual DbSet<TBL_OUTGOINGS> TBL_OUTGOINGS { get; set; }
        public virtual DbSet<TBL_PERSON> TBL_PERSON { get; set; }
        public virtual DbSet<TBL_PRODUCTACCEPTENCE> TBL_PRODUCTACCEPTENCE { get; set; }
        public virtual DbSet<TBL_PRODUCTFOLLOWING> TBL_PRODUCTFOLLOWING { get; set; }
        public virtual DbSet<TBL_PRODUCTMOVEMENT> TBL_PRODUCTMOVEMENT { get; set; }
        public virtual DbSet<TBL_PRODUCTS> TBL_PRODUCTS { get; set; }
        public virtual DbSet<TBL_ABOUTUS> TBL_ABOUTUS { get; set; }
        public virtual DbSet<TBL_CONNECTTION> TBL_CONNECTTION { get; set; }
        public virtual DbSet<TBL_ilceler> TBL_ilceler { get; set; }
        public virtual DbSet<TBL_iller> TBL_iller { get; set; }
    
        public virtual ObjectResult<urunkategori_Result> urunkategori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<urunkategori_Result>("urunkategori");
        }
    
        public virtual ObjectResult<string> maxkategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("maxkategory");
        }
    
        public virtual ObjectResult<maxBrand_Result> maxBrand()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<maxBrand_Result>("maxBrand");
        }
    }
}
