//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECNICALSERVICES
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTMOVEMENT
    {
        public int MOVEMENTID { get; set; }
        public Nullable<int> PRODUCT { get; set; }
        public Nullable<int> COSTUMER { get; set; }
        public Nullable<short> PERSON { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<short> NUMBER { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string PRODUCTSERIALNUMBER { get; set; }
    
        public virtual TBL_CURRENT TBL_CURRENT { get; set; }
        public virtual TBL_PERSON TBL_PERSON { get; set; }
        public virtual TBL_PRODUCTS TBL_PRODUCTS { get; set; }
    }
}
