//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECNICALSERVICES
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DEFECTDETAIL
    {
        public int ERRORID { get; set; }
        public Nullable<int> OPERATION { get; set; }
        public string PROBLEM { get; set; }
        public string EXPLANATION { get; set; }
        public Nullable<decimal> FIRSTPRICE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string OPS { get; set; }
    }
}
