//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECNICALSERVICES
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PRODUCTS()
        {
            this.TBL_PRODUCTMOVEMENT = new HashSet<TBL_PRODUCTMOVEMENT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string BRAND { get; set; }
        public Nullable<decimal> BUYINGPRICE { get; set; }
        public Nullable<decimal> SELLINGPRICE { get; set; }
        public Nullable<short> STOCK { get; set; }
        public Nullable<byte> CATEGORIES { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual TBL_CATEGORIES TBL_CATEGORIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PRODUCTMOVEMENT> TBL_PRODUCTMOVEMENT { get; set; }
    }
}
