//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECNICALSERVICES
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTACCEPTENCE
    {
        public int OPERATIONID { get; set; }
        public Nullable<int> CURRENT { get; set; }
        public Nullable<short> PERSON { get; set; }
        public Nullable<System.DateTime> ARRIVEDATE { get; set; }
        public Nullable<System.DateTime> ENDINGDATE { get; set; }
        public string PROSERNUM { get; set; }
        public Nullable<bool> PRODUCTSTATUS { get; set; }
        public string PRODUCTSTATUSDETAIL { get; set; }
    
        public virtual TBL_CURRENT TBL_CURRENT { get; set; }
        public virtual TBL_PERSON TBL_PERSON { get; set; }
    }
}
