//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECNICALSERVICES
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NOTES
    {
        public int ID { get; set; }
        public string HEADING { get; set; }
        public string CONTENT1 { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
