//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECNICALSERVICES
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BILLINFORMATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_BILLINFORMATION()
        {
            this.TBL_BILLDETAIL = new HashSet<TBL_BILLDETAIL>();
        }
    
        public int ID { get; set; }
        public string SERIES { get; set; }
        public string ITEMNO { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string TIME { get; set; }
        public string TAXOFFICE { get; set; }
        public Nullable<int> CURRENT { get; set; }
        public Nullable<short> PERSON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_BILLDETAIL> TBL_BILLDETAIL { get; set; }
        public virtual TBL_CURRENT TBL_CURRENT { get; set; }
        public virtual TBL_PERSON TBL_PERSON { get; set; }
    }
}
